# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8edadaa4776ae81bef8b6b7526c781ac6179e5dd5567aecdb125947096c6766a9bbd3d9b314e52dcaf6ec5efc83255357f282528b3bfa07874ad5a250a81f7d5

test:
  secret_key_base: 90af0a125cbcb3854b7009e2ab6d2c2651dd4574be25534a0cd6a423b38fbcc94bf13301d9fe9097ae75f895b6a97c9169f2ead1c70e5fb0aea9e201a0b85d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
